//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tetris.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_WAVE_APPLAUSE1              101
#define IDD_TETRIS_DIALOG               102
#define IDR_HTML_DLGRUSSSCORE           103
#define IDR_AVI                         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_HIGHSCORE            129
#define IDD_DIALOG_INPUTNAME            130
#define IDB_RUSS_BLUE                   131
#define IDB_RUSS_GREEN                  132
#define IDB_RUSS_GREY                   133
#define IDB_RUSS_HUMANBLUE              134
#define IDB_RUSS_HUMANRED               135
#define IDB_RUSS_ORANGE                 136
#define IDB_RUSS_PURPLE                 137
#define IDB_RUSS_RED                    138
#define IDB_RUSS_SCORE                  139
#define IDB_RUSS_SEABLUE                146
#define IDB_RUSS_THINBLUE               147
#define IDB_RUSS_THINGREEN              148
#define IDB_RUSS_THINPURPLE             149
#define IDB_RUSS_WHITE                  150
#define IDB_RUSS_YELLOW                 151
#define IDR_WAVE_APPLAUSE2              153
#define IDR_WAVE_APPLAUSE3              154
#define IDR_WAVE_APPLAUSE4              155
#define IDR_WAVE_CLEARROW               156
#define IDR_WAVE_GAMEOVER               157
#define IDR_WAVE_LEVELUP                158
#define IDR_WAVE_REBOTTOM               159
#define IDI_ICON_PURPLE                 161
#define IDI_ICON1                       163
#define IDI_ICON_CHOCA                  163
#define IDB_BITMAP1                     164
#define IDB_RUSS_CHOCA1                 164
#define IDB_BITMAP2                     165
#define IDB_RUSS_CHOCA2                 165
#define IDB_BITMAP3                     166
#define IDB_RUSS_CHOCA3                 166
#define IDB_BITMAP4                     167
#define IDB_RUSS_CHOCA4                 167
#define IDB_BITMAP5                     168
#define IDB_RUSS_CHOCA5                 168
#define IDB_BITMAP6                     169
#define IDB_RUSS_CHOCA6                 169
#define IDB_BITMAP7                     170
#define IDB_RUSS_CHOCA7                 170
#define IDB_BITMAP8                     171
#define IDB_RUSS_CHOCA8                 171
#define IDB_BITMAP9                     172
#define IDB_RUSS_CHOCA9                 172
#define IDB_BITMAP10                    173
#define IDB_RUSS_CHOCA10                173
#define IDB_BITMAP11                    174
#define IDB_RUSS_CHOCA11                174
#define IDB_BITMAP12                    175
#define IDB_RUSS_CHOCA12                175
#define IDB_BITMAP13                    176
#define IDB_RUSS_CHOCA13                176
#define IDB_BITMAP14                    177
#define IDB_RUSS_CHOCA14                177
#define IDI_ICON2                       178
#define IDI_ICON_SWEETS                 178
#define IDI_ICON_FRUIT                  179
#define IDB_BITMAP15                    180
#define IDB_RUSS_SWEETS1                180
#define IDB_BITMAP16                    181
#define IDB_RUSS_SWEETS2                181
#define IDB_BITMAP17                    182
#define IDB_RUSS_SWEETS3                182
#define IDB_BITMAP18                    183
#define IDB_RUSS_SWEETS4                183
#define IDB_BITMAP19                    184
#define IDB_RUSS_SWEETS5                184
#define IDB_BITMAP20                    185
#define IDB_RUSS_SWEETS6                185
#define IDB_BITMAP21                    186
#define IDB_RUSS_SWEETS7                186
#define IDB_BITMAP22                    187
#define IDB_RUSS_SWEETS8                187
#define IDB_BITMAP23                    188
#define IDB_RUSS_SWEETS9                188
#define IDB_BITMAP24                    189
#define IDB_RUSS_SWEETS10               189
#define IDB_BITMAP25                    190
#define IDB_RUSS_SWEETS12               190
#define IDB_BITMAP26                    191
#define IDB_RUSS_SWEETS13               191
#define IDB_BITMAP27                    192
#define IDB_RUSS_SWEETS15               192
#define IDB_BITMAP28                    193
#define IDB_RUSS_SWEETS14               193
#define IDB_BITMAP29                    194
#define IDB_RUSS_FRUIT1                 194
#define IDB_BITMAP30                    195
#define IDB_RUSS_FRUIT2                 195
#define IDB_BITMAP31                    196
#define IDB_RUSS_FRUIT3                 196
#define IDB_BITMAP32                    197
#define IDB_RUSS_FRUIT4                 197
#define IDB_BITMAP33                    198
#define IDB_RUSS_FRUIT5                 198
#define IDB_BITMAP34                    199
#define IDB_RUSS_FRUIT6                 199
#define IDB_BITMAP35                    200
#define IDB_RUSS_FRUIT7                 200
#define IDB_BITMAP36                    201
#define IDB_RUSS_FRUIT8                 201
#define IDB_BITMAP37                    202
#define IDB_RUSS_FRUIT9                 202
#define IDB_BITMAP38                    203
#define IDB_RUSS_FRUIT10                203
#define IDB_BITMAP39                    204
#define IDB_RUSS_FRUIT11                204
#define IDB_BITMAP40                    205
#define IDB_RUSS_FRUIT12                205
#define IDB_BITMAP41                    206
#define IDB_RUSS_FRUIT13                206
#define IDB_BITMAP42                    207
#define IDB_RUSS_FRUIT14                207
#define IDB_BITMAP43                    208
#define IDB_RUSS_SWEETS11               208
#define IDB_RUSS_ANIMAL1                209
#define IDB_RUSS_ANIMAL2                210
#define IDB_RUSS_ANIMAL3                211
#define IDB_RUSS_ANIMAL4                212
#define IDB_RUSS_ANIMAL5                213
#define IDB_RUSS_ANIMAL6                214
#define IDB_RUSS_ANIMAL7                215
#define IDI_ICON_ANIMAL                 216
#define IDI_ICON_HEART                  217
#define IDB_BITMAP45                    220
#define IDB_RUSS_HEART3                 220
#define IDB_BITMAP46                    221
#define IDB_RUSS_HEART8                 225
#define IDB_RUSS_HEART9                 226
#define IDB_RUSS_HEART10                227
#define IDB_RUSS_HEART11                228
#define IDB_RUSS_HEART12                229
#define IDB_RUSS_HEART13                230
#define IDB_RUSS_HEART14                231
#define IDB_RUSS_HEART15                232
#define IDR_SKINMAGIC1                  236
#define IDR_SKIN_CORONA                 237
#define IDR_SKIN_DEVIOR                 238
#define IDR_SKIN_XPSTEEL                239
#define IDR_SKINMAGIC2                  240
#define IDR_SKIN_FUTURAIII              240
#define IDB_RUSS_BACK1                  241
#define IDR_AVI1                        246
#define IDR_AVI2                        247
#define IDR_GIFBEER                     253
#define IDR_GIFBEAR                     253
#define IDR_GIFTEMP                     254
#define IDR_GIFRABBIT                   255
#define IDR_GIFMOUSE                    256
#define IDB_RUSS_MONEY1                 257
#define IDB_RUSS_MONEY2                 258
#define IDB_RUSS_MONEY3                 261
#define IDB_RUSS_MONEY4                 264
#define IDB_RUSS_MONEY5                 265
#define IDB_RUSS_MONEY6                 266
#define IDB_RUSS_MONEY7                 267
#define IDB_RUSS_BALL1                  268
#define IDB_RUSS_BALL2                  269
#define IDB_RUSS_BALL3                  270
#define IDB_RUSS_BALL4                  272
#define IDB_RUSS_BALL5                  273
#define IDB_RUSS_BALL6                  274
#define IDB_RUSS_BALL7                  275
#define IDB_RUSS_BALL8                  276
#define IDB_RUSS_SCORE_0                280
#define IDB_RUSS_SCORE_1                281
#define IDB_RUSS_SCORE_2                282
#define IDB_RUSS_SCORE_3                283
#define IDB_RUSS_SCORE_4                284
#define IDB_BITMAP49                    286
#define IDB_BITMAP44                    287
#define IDB_BITMAP50                    288
#define IDB_BITMAP47                    289
#define IDB_RUSS_SCORE_5                289
#define IDB_BITMAP48                    290
#define IDB_RUSS_SCORE_6                290
#define IDB_RUSS_SCORE_7                291
#define IDB_RUSS_SCORE_8                292
#define IDB_RUSS_SCORE_9                295
#define IDB_RUSS_SCORE_10               296
#define IDB_RUSS_SCORE_11               297
#define IDB_RUSS_SCORE_12               298
#define IDB_RUSS_SCORE_13               299
#define IDB_RUSS_SCORE_14               300
#define IDB_RUSS_SCORE_15               301
#define IDB_RUSS_SCORE_16               302
#define IDB_RUSS_SCORE_17               303
#define IDB_RUSS_SCORE_18               304
#define IDB_RUSS_SCORE_19               305
#define IDB_RUSS_SCORE_20               306
#define IDB_RUSS_SCORE_21               307
#define IDB_RUSS_SCORE_22               308
#define IDB_RUSS_SCORE_23               309
#define IDB_BITMAP51                    310
#define IDB_RUSS_SKIN1                  310
#define IDC_BTN_SCORE                   1000
#define IDC_BTN_PAUSE                   1001
#define IDC_BTN_MUSIC                   1002
#define IDC_STATIC_SCORE                1003
#define IDC_STATIC_LEVEL                1004
#define IDC_STATIC_NAME                 1006
#define IDC_BTN_CLRSCORE                1007
#define IDC_EDIT_NAME                   1009
#define IDC_RADIO_REC                   1012
#define IDC_RADIO_CHOCA                 1013
#define IDC_RADIO3                      1014
#define IDC_RADIO4                      1015
#define IDC_RADIO_SWEETS                1016
#define IDC_RADIO_FRUIT                 1017
#define IDC_RADIO5                      1018
#define IDC_RADIO6                      1019
#define IDC_RADIO_SIZE1                 1020
#define IDC_RADIO_SIZE2                 1021
#define IDC_BUTTON_END                  1022
#define IDC_RADIO_HEART                 1023
#define IDC_RUSS_BKPIC                  1024
#define IDC_RUSS_ANIMATE                1025
#define IDC_RUSS_PIC1                   1028
#define IDC_RUSS_PIC2                   1029
#define IDC_RUSS_PIC3                   1030
#define IDC_RUSS_PIC4                   1031
#define IDC_BTN_STOP                    1032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
